Update UserInterfaceSettingsActivity.kt
rebelonion/Dantotsu pull request #207
Opened 2024-02-27 13:43 UTC by sneazy-ibo

## Restart prompt for home layout changes
- added components require restart
- removed components require reload

→ prompt shows after changes in the home layout are done

2024-02-27 14:04 UTC, Sadwhy commented
I'm guessing it just adds a ok button that restarts the app

2024-02-27 14:34 UTC, sneazy-ibo commented
> I'm guessing it just adds a ok button that restarts the app

The ok button is from the Show/Hide Layouts on Home popup and not from the reload prompt

2024-02-27 14:39 UTC, Sadwhy commented
I completely forgot that `restartApp()` was a custom function and not something from android. Just use "Done" or "Confirm" isn't of ok. Looks weird.

2024-02-29 09:25 UTC, Sadwhy commented
Change and reload? :trollface:

2024-02-29 09:34 UTC, rebelonion requested changes

2024-02-29 09:34 UTC, rebelonion commented on app/src/main/java/ani/dantotsu/settings/UserInterfaceSettingsActivity.kt
>                  }.show()
you didn't delete the old function

2024-02-29 18:11 UTC, aayush2622 approved these changes
all good

2024-02-29 18:42 UTC, merged