Made the skip button dissappear after 5 seconds with a setting to turn it off
rebelonion/Dantotsu pull request #224
Opened 2024-03-07 15:27 UTC by JohnVictoryz

This is a enhancement feature that was posed by #150 
This PR if merged can close #150 

What i did to verify the functionality:

- I tested the functionality using a google pixel vm provided by Android Studio
- I tested it on a OnePlus X phone using [LineageOS](https://lineageos.org/)  (Android Version: 13)
- I tested it on a LG G6 Thinq Running Stock Android (Android Version: 9)
- Checked for any bugs and not wanted behavior

What i Added:

- A setting to turn this feature on or off
- Making it disappear

2024-03-07 23:33 UTC, rebelonion requested changes
why so many unused imports?
could you please clean those up?

2024-03-08 05:02 UTC, JohnVictoryz commented
> why so many unused imports?
> could you please clean those up?

Yes sorry

2024-03-08 16:06 UTC, rebelonion requested changes

2024-03-08 16:06 UTC, rebelonion commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                    timer.start()
this could launch a bunch of timers while the first one is counting down

2024-03-08 18:48 UTC, sneazy-ibo commented
@JohnVictoryz are you in the dc server?

2024-03-08 19:06 UTC, JohnVictoryz commented
> @JohnVictoryz are you in the dc server?

Yes I am

2024-03-08 19:09 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                        override fun onTick(millisUntilFinished: Long) {
This is so in case you skip ahead from the time stamp and didn't hit the skip time stamp button before the 5 second timer to automatically hide the button

2024-03-08 19:11 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                    timer.start()
Didn't think about that one sorry

2024-03-08 19:11 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                            dissappeared = 1
No I just thought about this

2024-03-09 01:41 UTC, sneazy-ibo commented
> > @JohnVictoryz are you in the dc server?
> 
> Yes I am

What's your name there I wanna ask you smth

2024-03-09 07:58 UTC, JohnVictoryz commented
> > > @JohnVictoryz are you in the dc server?
> > 
> > 
> > Yes I am
> 
> What's your name there I wanna ask you smth

tutelwastaken

2024-03-09 21:16 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                fun DissapearSkip(){
it's a nested function because it needs to return `if (new == null)` but not exit the whole function only exit this so it can continue update time stamp

2024-03-10 17:47 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                    timer.start()
Resolved in new commit

2024-03-10 17:47 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                            dissappeared = 1
Resolved in new commit

2024-03-10 17:47 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +    private var dissappeared = 0
Resolved in new commit

2024-03-11 09:00 UTC, rebelonion requested changes

2024-03-11 09:00 UTC, rebelonion commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                    var timer: CountDownTimer? = null
this will still create a new timer every time the function is run.

2024-03-11 15:38 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                    var timer: CountDownTimer? = null
Sorry i didn't notice

2024-03-11 19:05 UTC, JohnVictoryz commented on app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt
> +                    var timer: CountDownTimer? = null
Resolved hopefully in new commit

2024-03-13 12:55 UTC, rebelonion approved these changes

2024-03-13 12:56 UTC, merged